name: Slack Notification

on:
  workflow_dispatch:
jobs:
  wait-for-releases:
    name: Wait for Docker, Homebrew, RPM and Platform executables Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@v2
  notify-complete-success:
    needs: [ wait-for-releases ]
    name: Notify Release Completed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_COLOR: "#36a64f"
          SLACK_USERNAME: CLI Release Bot
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_TITLE: 'Twilio CLI'
          SLACK_MESSAGE: 'Release Completed.'
          MSG_MINIMAL: actions url 
